"""fixing an column of the table

Revision ID: 1928ee293e93
Revises: 77c85714e79c
Create Date: 2022-02-09 11:12:49.718870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1928ee293e93'
down_revision = '77c85714e79c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('vaccine_cards_name_key', 'vaccine_cards', type_='unique')
    op.create_unique_constraint(None, 'vaccine_cards', ['cpf'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vaccine_cards', type_='unique')
    op.create_unique_constraint('vaccine_cards_name_key', 'vaccine_cards', ['name'])
    # ### end Alembic commands ###
