"""creating the vaccine_cards table

Revision ID: 77c85714e79c
Revises: 
Create Date: 2022-02-08 16:31:37.927815

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '77c85714e79c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vaccine_cards',
    sa.Column('cpf', sa.String(length=11), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('first_shot_date', sa.DateTime(), nullable=True),
    sa.Column('second_shot_date', sa.DateTime(), nullable=True),
    sa.Column('vaccine_name', sa.String(length=50), nullable=False),
    sa.Column('health_unit_name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('cpf'),
    sa.UniqueConstraint('name')
    )
    op.drop_table('salgados')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('salgados',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.VARCHAR(length=60), autoincrement=False, nullable=False),
    sa.Column('preco', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='salgados_pkey'),
    sa.UniqueConstraint('nome', name='salgados_nome_key')
    )
    op.drop_table('vaccine_cards')
    # ### end Alembic commands ###
